// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExtractorSemanticoApi.Dominio;

public partial class ExtractedDatum
{
    public int DataId { get; set; }

    public int ReviewId { get; set; }

    public string Type { get; set; }

    public string Value { get; set; }

    public string Subtype { get; set; }

    public string Metadata { get; set; }

    public virtual Review Review { get; set; }
}