// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExtractorSemanticoApi.Dominio;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public string Category { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}