// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExtractorSemanticoApi.Dominio;

public partial class Sentiment
{
    public int SentimentId { get; set; }

    public int ReviewId { get; set; }

    public string Aspect { get; set; }

    public string SentimentType { get; set; } = string.Empty; // POSITIVO, NEUTRAL, NEGATIVO

    public float? Confidence { get; set; }

    public virtual Review Review { get; set; }
}